### ISSUE TITLE
Old Style Numerals

### ISSUE THREAD

**Issue by JNord03** [productiontype/NewsReader#13]
Hell Production Type,
thank you very much for this outstanding typeface. Are there any plans to expand it by adding Old Style numerals (and maybe even Small capitals)?

**Comment by productiontype** [comment]
Hello! As of today, there are no plans to add old style figures nore small capitals. However you can design your own and even submit a pull request for them to be added to the upstream repo. Thanks for your interest in Newsreader!

**Comment by mbana** [comment]
I really wish you added small capitals and old style numerals as well.

How much money do you need to add them, @productiontype?

**Comment by productiontype** [comment]
Hi! We'd be happy to extend Newsreader. Please reach out to licensing@productiontype.com so we can discuss. Thanks!
